"""
Regenerate kb/baseline.yaml from normal-labeled swings.

Runs the feature orchestrator on every swing labeled type: normal in
data/labels.yaml, computes per-feature mean/stddev/n across those
swings, and writes the result to kb/baseline.yaml.

Regenerate after:
- Refilming or relabeling normal swings
- Changing any feature extractor
- Changing the schema

Usage:
    python scripts/regenerate_baseline.py
"""

from __future__ import annotations

import math
import re
import statistics
from pathlib import Path

import yaml

from golf_diagnostic.features.landmarks import Handedness
from golf_diagnostic.features.orchestrator import compute_swing_features
from golf_diagnostic.features.schema import FEATURE_NAMES
from golf_diagnostic.pose.extractor import load_pose


REPO_ROOT = Path(__file__).resolve().parent.parent
LABELS_PATH = REPO_ROOT / "data" / "labels.yaml"
POSE_DIR = REPO_ROOT / "data" / "processed"
SEG_SUMMARY_PATH = POSE_DIR / "segmentation_summary.txt"
OUTPUT_PATH = REPO_ROOT / "kb" / "baseline.yaml"

CHECKPOINT_RE = re.compile(
    r"(swing_\d+).*?P1=\s*(\d+).*?P4=\s*(\d+).*?P7=\s*(\d+).*?P10=\s*(\d+)"
)


def load_checkpoints() -> dict[str, dict[str, int]]:
    """Parse segmentation_summary.txt into {swing_id: {P1,P4,P7,P10}}."""
    text = SEG_SUMMARY_PATH.read_text()
    out: dict[str, dict[str, int]] = {}
    for line in text.splitlines():
        m = CHECKPOINT_RE.search(line)
        if not m:
            continue
        swing_id, p1, p4, p7, p10 = m.groups()
        out[swing_id] = {"P1": int(p1), "P4": int(p4), "P7": int(p7), "P10": int(p10)}
    return out


def load_normal_swing_ids() -> list[str]:
    with LABELS_PATH.open() as f:
        labels = yaml.safe_load(f)
    return sorted(sid for sid, meta in labels.items() if meta.get("type") == "normal")


def compute_baseline() -> dict[str, dict]:
    swing_ids = load_normal_swing_ids()
    checkpoints_by_swing = load_checkpoints()

    print(f"Baseline swings: {len(swing_ids)}")
    per_feature_values: dict[str, list[float]] = {name: [] for name in FEATURE_NAMES}

    for sid in swing_ids:
        if sid not in checkpoints_by_swing:
            raise RuntimeError(f"No checkpoint entry for {sid} in {SEG_SUMMARY_PATH}")
        pose_path = POSE_DIR / f"{sid}_pose.npz"
        if not pose_path.exists():
            raise RuntimeError(f"Missing pose cache: {pose_path}")

        pose = load_pose(pose_path)
        features = compute_swing_features(
            pose, checkpoints_by_swing[sid], Handedness.RIGHT_HANDED
        )
        for name in FEATURE_NAMES:
            v = features.get(name)
            if math.isfinite(v):
                per_feature_values[name].append(v)

    out: dict[str, dict] = {}
    for name in FEATURE_NAMES:
        vals = per_feature_values[name]
        n = len(vals)
        if n == 0:
            out[name] = {"mean": None, "stddev": None, "n": 0}
        elif n == 1:
            out[name] = {"mean": round(vals[0], 4), "stddev": None, "n": 1}
        else:
            out[name] = {
                "mean": round(statistics.fmean(vals), 4),
                "stddev": round(statistics.stdev(vals), 4),
                "n": n,
            }
    return out


HEADER = """\
# Baseline feature statistics for KB z-score indicators.
#
# Generated by scripts/regenerate_baseline.py from swings labeled
# type: normal in data/labels.yaml. Used by KB indicators with
# mode: zscore.
#
# Regenerate after refilming normal swings, changing any extractor,
# or changing the schema. Committing changes to this file should be
# a deliberate action, not a side effect.
#
# Fields:
#   mean:   arithmetic mean across baseline swings (finite values only)
#   stddev: sample stddev across baseline swings (null if n < 2)
#   n:      count of finite values contributing (null mean if n == 0)
"""


def main() -> None:
    baseline = compute_baseline()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w") as f:
        f.write(HEADER)
        yaml.safe_dump(baseline, f, sort_keys=True, default_flow_style=False)
    print(f"Wrote {OUTPUT_PATH}")
    print(f"Features: {len(baseline)}")
    zero_n = [name for name, v in baseline.items() if v["n"] == 0]
    if zero_n:
        print(f"WARNING: {len(zero_n)} features have n=0 (all NaN):")
        for name in zero_n:
            print(f"  {name}")


if __name__ == "__main__":
    main()